channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::r-base=4.1  # Specify the R version if needed
  - conda-forge::r-optparse
  - conda-forge::r-ggplot2
  - conda-forge::r-caret
  - conda-forge::r-reshape2
  - conda-forge::r-data.table
  - bioconda::bioconductor-rtracklayer
  - bioconda::bioconductor-genomicranges
  - bioconda::bioconductor-derfinder
  - bioconda::bioconductor-biocparallel
